/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeletePersonnelArgs } from "./DeletePersonnelArgs";
import { PersonnelFindManyArgs } from "./PersonnelFindManyArgs";
import { PersonnelFindUniqueArgs } from "./PersonnelFindUniqueArgs";
import { Personnel } from "./Personnel";
import { PersonnelService } from "../personnel.service";

@graphql.Resolver(() => Personnel)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class PersonnelResolverBase {
  constructor(
    protected readonly service: PersonnelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Personnel",
    action: "read",
    possession: "any",
  })
  async _personnelsMeta(
    @graphql.Args() args: PersonnelFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Personnel])
  @nestAccessControl.UseRoles({
    resource: "Personnel",
    action: "read",
    possession: "any",
  })
  async personnels(
    @graphql.Args() args: PersonnelFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Personnel[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Personnel",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Personnel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Personnel",
    action: "read",
    possession: "own",
  })
  async personnel(
    @graphql.Args() args: PersonnelFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Personnel | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Personnel",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Personnel)
  @nestAccessControl.UseRoles({
    resource: "Personnel",
    action: "delete",
    possession: "any",
  })
  async deletePersonnel(
    @graphql.Args() args: DeletePersonnelArgs
  ): Promise<Personnel | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
