/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsDate, IsOptional, ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { PatientWhereUniqueInput } from "../../patient/base/PatientWhereUniqueInput";
import { TreatmentWhereUniqueInput } from "../../treatment/base/TreatmentWhereUniqueInput";
@InputType()
class AppointmentUpdateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  date?: Date;

  @ApiProperty({
    required: false,
    type: () => PatientWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PatientWhereUniqueInput)
  @IsOptional()
  @Field(() => PatientWhereUniqueInput, {
    nullable: true,
  })
  patient?: PatientWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TreatmentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TreatmentWhereUniqueInput)
  @IsOptional()
  @Field(() => TreatmentWhereUniqueInput, {
    nullable: true,
  })
  treatment?: TreatmentWhereUniqueInput | null;
}
export { AppointmentUpdateInput };
